# HydroEVENTS.cmake
# based on HydroEVENTS.pri by Justin
# Usage:
#   include(path/to/HydroEVENTS.cmake)
#   simcenter_add_hydro_events(<target>)

set(EVENTS_MODULE_DIR "${CMAKE_CURRENT_LIST_DIR}")

function(simcenter_add_hydro_events target)
  set(dir "${EVENTS_MODULE_DIR}")
  
  target_include_directories(${target} PRIVATE
    "${dir}/EDP"
    "${dir}/EVENTS"
    "${dir}/EVENTS/Common"
    "${dir}/EVENTS/GeoClawOpenFOAM"
    "${dir}/EVENTS/WaveDigitalFlume"
    "${dir}/EVENTS/coupledDigitalTwin"
    "${dir}/EVENTS/MPM"
    "${dir}/EVENTS/MPMEvent"
    "${dir}/EVENTS/TaichiEvent"
    "${dir}/EVENTS/Celeris"
    "${dir}/EVENTS/NOAA"
    "${dir}/EVENTS/StochasticWaveModel"
    "${dir}/EVENTS/StochasticWaveModel/include"
    "${dir}/EVENTS/StochasticWaveModel/src"
    "${dir}/SlidingStackedWidget"
  )

  set(SOURCES 
    "${dir}/EVENTS/HydroEventSelection.cpp"
    "${dir}/EVENTS/GeoClawOpenFOAM/hydroerror.cpp"
    "${dir}/EVENTS/GeoClawOpenFOAM/GeoClawOpenFOAM.cpp"
    "${dir}/EVENTS/GeoClawOpenFOAM/H20utilities/h20utilities.cpp"
    "${dir}/EVENTS/GeoClawOpenFOAM/boundary.cpp"
    "${dir}/EVENTS/GeoClawOpenFOAM/boundarydata.cpp"
    "${dir}/EVENTS/GeoClawOpenFOAM/buildings.cpp"
    "${dir}/EVENTS/GeoClawOpenFOAM/cfdsolvers/openfoam/openfoam.cpp"
    "${dir}/EVENTS/GeoClawOpenFOAM/cfdsolvers/openfoam/systemfiles.cpp"
    "${dir}/EVENTS/GeoClawOpenFOAM/floatingbds.cpp"
    "${dir}/EVENTS/GeoClawOpenFOAM/initialconalpha.cpp"
    "${dir}/EVENTS/GeoClawOpenFOAM/initialconpres.cpp"
    "${dir}/EVENTS/GeoClawOpenFOAM/initialconvel.cpp"
    "${dir}/EVENTS/GeoClawOpenFOAM/materials.cpp"
    "${dir}/EVENTS/GeoClawOpenFOAM/meshing.cpp"
    "${dir}/EVENTS/GeoClawOpenFOAM/qt3dframe.cpp"
    "${dir}/EVENTS/GeoClawOpenFOAM/scenemodifier.cpp"
    "${dir}/EVENTS/GeoClawOpenFOAM/solver.cpp"
    "${dir}/EVENTS/GeoClawOpenFOAM/swcfdint.cpp"
    "${dir}/EVENTS/GeoClawOpenFOAM/swsolvers/geoclaw/geoclaw.cpp"
    "${dir}/EVENTS/GeoClawOpenFOAM/postprocess.cpp"
    "${dir}/EVENTS/coupledDigitalTwin/CoupledDigitalTwin.cpp"
    "${dir}/EVENTS/coupledDigitalTwin/SettingsDigitalTwin.cpp"
    "${dir}/EVENTS/coupledDigitalTwin/OutputsDigitalTwin.cpp"
    "${dir}/EVENTS/coupledDigitalTwin/OpenSeesDigitalTwin.cpp"
    "${dir}/EVENTS/coupledDigitalTwin/OpenFOAM_DigitalTwin.cpp"
    "${dir}/EVENTS/coupledDigitalTwin/VisualizeDigitalTwin.cpp"
    "${dir}/EVENTS/MPM/MPM.cpp"
    "${dir}/EVENTS/MPM/BoundaryMPM.cpp"
    "${dir}/EVENTS/MPM/BoundariesMPM.cpp"
    "${dir}/EVENTS/MPM/OutputsMPM.cpp"
    "${dir}/EVENTS/MPM/SensorsMPM.cpp"
    "${dir}/EVENTS/MPM/SensorMPM.cpp"
    "${dir}/EVENTS/MPM/BodiesMPM.cpp"
    "${dir}/EVENTS/MPM/SettingsMPM.cpp"
    "${dir}/EVENTS/MPM/MaterialMPM.cpp"
    "${dir}/EVENTS/MPM/GeometriesMPM.cpp"
    "${dir}/EVENTS/MPM/GeometryMPM.cpp"
    "${dir}/EVENTS/MPM/AlgorithmMPM.cpp"
    "${dir}/EVENTS/MPM/PartitionsMPM.cpp"
    "${dir}/EVENTS/MPM/PartitionMPM.cpp"
    "${dir}/EVENTS/MPM/ResultsMPM.cpp"
    "${dir}/EVENTS/MPM/GeometryAI.cpp"
    "${dir}/EVENTS/MPM/SPH.cpp"
    "${dir}/EVENTS/MPM/CaseSPH.cpp"
    "${dir}/EVENTS/MPM/ExecutionSPH.cpp"
    "${dir}/EVENTS/MPMEvent/MPMEvent.cpp"
    "${dir}/EVENTS/MPMEvent/BasicMPMEvent.cpp"
    "${dir}/EVENTS/TaichiEvent/TaichiEvent.cpp"
    "${dir}/EVENTS/TaichiEvent/BasicTaichiEvent.cpp"
    "${dir}/EVENTS/Celeris/CelerisDomain.cpp"
    "${dir}/EVENTS/Celeris/CelerisSolver.cpp"
    "${dir}/EVENTS/Celeris/CelerisTaichi.cpp"
    "${dir}/EVENTS/Celeris/CelerisTaichiEvent.cpp"
    "${dir}/EVENTS/NOAA/DigitalCoast.cpp"
    "${dir}/EVENTS/StochasticWaveModel/src/StochasticWaveInput.cpp"
    "${dir}/EVENTS/StochasticWaveModel/src/Jonswap.cpp"
    "${dir}/EVENTS/WaveDigitalFlume/WaveDigitalFlume.cpp"
    "${dir}/EVENTS/Common/projectsettings.cpp"
    "${dir}/EVENTS/Common/bathymetry.cpp"
  )

  set(HEADERS
    "${dir}/EVENTS/HydroEventSelection.h"
    "${dir}/EVENTS/GeoClawOpenFOAM/hydroerror.h"
    "${dir}/EVENTS/GeoClawOpenFOAM/H20utilities/h20utilities.h"
    "${dir}/EVENTS/GeoClawOpenFOAM/boundary.h"
    "${dir}/EVENTS/GeoClawOpenFOAM/boundarydata.h"
    "${dir}/EVENTS/GeoClawOpenFOAM/buildings.h"
    "${dir}/EVENTS/GeoClawOpenFOAM/floatingbds.h"
    "${dir}/EVENTS/GeoClawOpenFOAM/initialconalpha.h"
    "${dir}/EVENTS/GeoClawOpenFOAM/initialconpres.h"
    "${dir}/EVENTS/GeoClawOpenFOAM/initialconvel.h"
    "${dir}/EVENTS/GeoClawOpenFOAM/GeoClawOpenFOAM.h"
    "${dir}/EVENTS/GeoClawOpenFOAM/materials.h"
    "${dir}/EVENTS/GeoClawOpenFOAM/meshing.h"
    "${dir}/EVENTS/GeoClawOpenFOAM/qt3dframe.h"
    "${dir}/EVENTS/GeoClawOpenFOAM/scenemodifier.h"
    "${dir}/EVENTS/GeoClawOpenFOAM/solver.h"
    "${dir}/EVENTS/GeoClawOpenFOAM/swcfdint.h"
    "${dir}/EVENTS/GeoClawOpenFOAM/swsolvers/geoclaw/geoclaw.h"
    "${dir}/EVENTS/GeoClawOpenFOAM/cfdsolvers/openfoam/openfoam.h"
    "${dir}/EVENTS/GeoClawOpenFOAM/postprocess.h"
    "${dir}/EVENTS/coupledDigitalTwin/CoupledDigitalTwin.h"
    "${dir}/EVENTS/coupledDigitalTwin/SettingsDigitalTwin.h"
    "${dir}/EVENTS/coupledDigitalTwin/OutputsDigitalTwin.h"
    "${dir}/EVENTS/coupledDigitalTwin/OpenSeesDigitalTwin.h"
    "${dir}/EVENTS/coupledDigitalTwin/OpenFOAM_DigitalTwin.h"
    "${dir}/EVENTS/coupledDigitalTwin/VisualizeDigitalTwin.h"
    "${dir}/EVENTS/MPM/MPM.h"
    "${dir}/EVENTS/MPM/BoundaryMPM.h"
    "${dir}/EVENTS/MPM/BoundariesMPM.h"
    "${dir}/EVENTS/MPM/OutputsMPM.h"
    "${dir}/EVENTS/MPM/SensorsMPM.h"
    "${dir}/EVENTS/MPM/SensorMPM.h"
    "${dir}/EVENTS/MPM/BodiesMPM.h"
    "${dir}/EVENTS/MPM/SettingsMPM.h"   
    "${dir}/EVENTS/MPM/MaterialMPM.h"
    "${dir}/EVENTS/MPM/GeometriesMPM.h"
    "${dir}/EVENTS/MPM/GeometryMPM.h"
    "${dir}/EVENTS/MPM/AlgorithmMPM.h"
    "${dir}/EVENTS/MPM/PartitionsMPM.h"   
    "${dir}/EVENTS/MPM/PartitionMPM.h"  
    "${dir}/EVENTS/MPM/ResultsMPM.h"
    "${dir}/EVENTS/MPM/GeometryAI.h"
    "${dir}/EVENTS/MPM/SPH.h"
    "${dir}/EVENTS/MPM/CaseSPH.h"
    "${dir}/EVENTS/MPM/ExecutionSPH.h"
    "${dir}/EVENTS/MPMEvent/MPMEvent.h"
    "${dir}/EVENTS/MPMEvent/BasicMPMEvent.h"
    "${dir}/EVENTS/TaichiEvent/TaichiEvent.h"
    "${dir}/EVENTS/TaichiEvent/BasicTaichiEvent.h"
    "${dir}/EVENTS/Celeris/CelerisDomain.h"
    "${dir}/EVENTS/Celeris/CelerisSolver.h"
    "${dir}/EVENTS/Celeris/CelerisTaichi.h"
    "${dir}/EVENTS/Celeris/CelerisTaichiEvent.h"
    "${dir}/EVENTS/NOAA/DigitalCoast.h"
    "${dir}/EVENTS/StochasticWaveModel/include/StochasticWaveInput.h"
    "${dir}/EVENTS/StochasticWaveModel/include/Jonswap.h"
    "${dir}/EVENTS/WaveDigitalFlume/WaveDigitalFlume.h"
    "${dir}/EVENTS/Common/projectsettings.h"
    "${dir}/EVENTS/Common/bathymetry.h"
  )

  set(FORMS
    "${dir}/EVENTS/GeoClawOpenFOAM/GeoClawOpenFOAM_copy.ui"
    "${dir}/EVENTS/GeoClawOpenFOAM/boundary.ui"
    "${dir}/EVENTS/GeoClawOpenFOAM/boundarydata.ui"
    "${dir}/EVENTS/GeoClawOpenFOAM/boundarydata_copy.ui"
    "${dir}/EVENTS/GeoClawOpenFOAM/buildings.ui"
    "${dir}/EVENTS/GeoClawOpenFOAM/floatingbds.ui"
    "${dir}/EVENTS/GeoClawOpenFOAM/initialconalpha.ui"
    "${dir}/EVENTS/GeoClawOpenFOAM/initialconpres.ui"
    "${dir}/EVENTS/GeoClawOpenFOAM/initialconvel.ui"
    "${dir}/EVENTS/GeoClawOpenFOAM/GeoClawOpenFOAM.ui"
    "${dir}/EVENTS/GeoClawOpenFOAM/materials.ui"
    "${dir}/EVENTS/GeoClawOpenFOAM/meshing.ui"
    "${dir}/EVENTS/GeoClawOpenFOAM/projectsettings_old.ui"
    "${dir}/EVENTS/GeoClawOpenFOAM/solver.ui"
    "${dir}/EVENTS/GeoClawOpenFOAM/swcfdint.ui"
    "${dir}/EVENTS/GeoClawOpenFOAM/postprocess.ui"
    "${dir}/EVENTS/WaveDigitalFlume/WaveDigitalFlume.ui"
    "${dir}/EVENTS/Common/projectsettings.ui"
    "${dir}/EVENTS/Common/bathymetry.ui"
  )

  set(RESOURCES
    resources.qrc
  )

  target_sources(${target} PRIVATE ${SOURCES} ${HEADERS} ${FORMS} ${RESOURCES})
  
endfunction()

